# Generated by Django 4.2.2 on 2023-07-05 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['nombre'], 'permissions': (('is_admin', 'Can administrate'),)},
        ),
    ]
