# Generated by Django 4.2.2 on 2023-07-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_animal_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='estilo',
            field=models.CharField(choices=[('img-larga', 'img-larga'), ('img-corta', 'img-corta')], help_text='Tamaño con el que se mostrara la imagen', max_length=100),
        ),
    ]
