# Generated by Django 4.2.2 on 2023-07-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_imagen_estilo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitat',
            name='continente',
            field=models.CharField(choices=[('AF', 'Africa'), ('AS', 'Asia'), ('AM', 'America'), ('EU', 'Europa'), ('OC', 'Oceania'), ('AN', 'Antartida'), ('M', 'Mundo')], max_length=2),
        ),
    ]
